In [1]:
import numpy as np

In [16]:
a = np.array([1, 2, 4])
print(a, type(a))
a = np.array([[1, 2], [3, 4]])
print(a)
a = np.array([1, 2, 3, 4], ndmin=2)
print(a)
a = np.array([1, 2, 3, 4], dtype=np.complex)
print(a)

[1 2 4] <class 'numpy.ndarray'>
[[1 2]
 [3 4]]
[[1 2 3 4]]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [30]:
dt = np.dtype([('name', 'U20'), ('age', 'i8')])
a = np.array([('ling', 10), ('fang', 20), ('yuan', 30)], dtype=dt)
print(a, a['age'], a['name'])

[('ling', 10) ('fang', 20) ('yuan', 30)] [10 20 30] ['ling' 'fang' 'yuan']


In [38]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
a.shape = (3, 2)
print(a)
b = a.reshape(2, 3)
print(b)
print(b.ndim)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
2


In [44]:
a = np.arange(24)
print(a.ndim)
b = a.reshape(2, 4, 3)
print(b)
print(b.itemsize)
print(b.flags)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
4
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [53]:
x = np.empty([3, 2], dtype='i4')
print('np.empty\n', x)
x = np.zeros([3, 2], dtype='i4')
print('np.zeros\n', x)
x = np.zeros([2, 2], dtype=[('x', 'i4'), ('y', 'i4')])
print('np.zeros\n', x)
x = np.ones([3, 3], dtype='i4')
print('np.ones\n', x)

np.empty
 [[0 0]
 [0 0]
 [0 0]]
np.zeros
 [[0 0]
 [0 0]
 [0 0]]
np.zeros
 [[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
np.ones
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [56]:
x = [2, 3, 5]
a = np.asarray(x, dtype='f')
print(a)

[2. 3. 5.]


In [61]:
s = b'Hello World'
a = np.frombuffer(s, dtype='S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [64]:
li = range(5)
x = np.fromiter(li, dtype='f')
print(x)

[0. 1. 2. 3. 4.]


In [65]:
x = np.arange(2, 20, 3, dtype='f')
print(x)

[ 2.  5.  8. 11. 14. 17.]


In [73]:
x = np.linspace(1, 10, 10, endpoint=False, retstep=True, dtype='f')
print(x)

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1], dtype=float32), 0.9)


In [75]:
x = np.logspace(1, 4, 4, endpoint=True, base=2, dtype='f')
print(x)

[ 2.  4.  8. 16.]


In [94]:
# 切片
a = np.arange(10)
s = slice(2, 7, 2)
print(a[s], a[2:7:2])
a = np.array([[1, 2, 4], [3, 5, 6], [7, 8, 9]])
print(a[::2, 1:3])
print(a[..., 1:3])

[2 4 6] [2 4 6]
[[2 4]
 [8 9]]
[[2 4]
 [5 6]
 [8 9]]


In [95]:
# 高级索引
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(y)

[1 4 5]


In [97]:
# 布尔索引
x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9,  10,  11]])
print(x)
print(x[x > 5])
a = np.array([np.nan,  1,2,np.nan,3,4,5])  
print(a)
print(a[~np.isnan(a)])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 6  7  8  9 10 11]
[nan  1.  2. nan  3.  4.  5.]
[1. 2. 3. 4. 5.]


In [99]:
# 广播
a = np.array([1, 2, 3, 4]).reshape(1, 4)
b = np.array([10, 20, 30, 40]).reshape(4, 1)
c = a * b
print(c)

[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]
 [ 40  80 120 160]]


In [106]:
# 迭代
a = np.arange(0, 60, 5).reshape(3, 4)
print(a)
for x in np.nditer(a, order='F', op_flags=['readwrite']):
    x[...] = 2 * x
    print(x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0
40
80
10
50
90
20
60
100
30
70
110


In [110]:
# 广播迭代
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print('第一个数组：')
print(a)
print('第二个数组：')
b = np.array([1,  2,  3,  4], dtype=int)
print(b)
print('修改后的数组是：')
for x, y in np.nditer([a, b]):
    print("%d:%d" % (x, y))

第一个数组：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
第二个数组：
[1 2 3 4]
修改后的数组是：
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [120]:
a = np.array([0,30,45,60,90])
print(np.sin(a * np.pi / 180))
print(np.cos(a * np.pi / 180))
print(np.tan(a * np.pi / 180))
sin = np.sin(a * np.pi / 180)
print(sin)
print(np.arcsin(sin))
print(np.degrees(np.arcsin(sin)))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
[0.         0.5        0.70710678 0.8660254  1.        ]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[ 0. 30. 45. 60. 90.]


In [131]:
a = np.array([1.0, 5.55,  123,  0.567,  25.532])
print(np.around(a, 1))
print(np.floor(a))
print(np.ceil(a))

[  1.    5.6 123.    0.6  25.5]
[  1.   5. 123.   0.  25.]
[  1.   6. 123.   1.  26.]


In [145]:
a = np.array([0.25,  1.33,  2.5,  0.1,  100.0], dtype='i8')
print(a)
print(np.reciprocal(a))

[  0   1   2   0 100]
[-9223372036854775808                    1                    0
 -9223372036854775808                    0]


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in reciprocal
  This is separate from the ipykernel package so we can avoid doing imports until
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in reciprocal
  This is separate from the ipykernel package so we can avoid doing imports until


In [147]:
# 标准差
print(np.std([1,2,3,4]))
# 方差
print(np.var([1,2,3,4]))

1.118033988749895
1.25


In [150]:
import numpy.matlib
print(np.matlib.identity(5, dtype='f'))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [154]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]])
print(a)
print(b)
print(np.dot(a,b))
print(a * b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[37 40]
 [85 92]]
[[11 24]
 [39 56]]


In [157]:
a = np.arange(8).reshape(2,2,2) 
b = np.arange(4).reshape(2,2) 
print('a:')
print(a)
print('b:')
print(b)
print('matmul:')
print(np.matmul(a,b))

a:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
b:
[[0 1]
 [2 3]]
matmul:
[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]
